# Generated by Django 3.1.7 on 2021-03-24 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dsrs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resource',
            options={'ordering': ('-revenue',)},
        ),
        migrations.AlterModelTable(
            name='resource',
            table=None,
        ),
    ]
